#!/usr/bin/env sh
CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -pedantic -std=c89"

# Stop on first error and log all commands
set -ex

# Compile demonstration tests
$CC $CFLAGS -o demo/demo0.t demo/demo0.t.c
$CC $CFLAGS -o demo/demo1.t demo/demo1.t.c
$CC $CFLAGS -o demo/demo2.t demo/demo2.t.c
$CC $CFLAGS -o demo/demo3.t demo/demo3.t.c
$CC $CFLAGS -o demo/demo4.t demo/demo4.t.c
$CC $CFLAGS -o demo/demo5.t demo/demo5.t.c

# Compile walter tests
$CC $CFLAGS -o tests tests.c

# Run tests
./tests
