#!/usr/bin/env sh
set -ex # Stop on first error and log all commands

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -pedantic -std=c89"

cc -o demo.t demo.t.c
cc -o demo/demo0.t demo/demo0.t.c
cc -o demo/demo1.t demo/demo1.t.c
cc -o demo/demo2.t demo/demo2.t.c
cc -o demo/demo3.t demo/demo3.t.c
cc -o demo/demo4.t demo/demo4.t.c
cc -o demo/demo5.t demo/demo5.t.c
